version: 2
updates:
  # 1. Maintain GitHub Actions CI/CD workflows (Grouped into 1 PR)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 2

  # 2. Maintain Flutter & Dart packages (Grouped into 1 PR)
  - package-ecosystem: "pub"
    directory: "/flutter_app"
    schedule:
      interval: "weekly"
    groups:
      flutter-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 2

  # 3. Maintain Python Machine Learning dependencies (Grouped into 1 PR)
  - package-ecosystem: "pip"
    directory: "/model_pipeline"
    schedule:
      interval: "monthly"
    groups:
      python-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 2
